version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PWD}
      MYSQL_DATABASE: ${DB_NAME}
      TZ: Asia/Seoul
    command: ${DB_CONFIG}
    ports:
      - "3306:3306"
    volumes:
      - ${DB_PATH}:/var/lib/mysql:rw

  redis:
    image: redis:7.0.5
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
    command:
      - bash
      - -c
      - |
        npm run dev
    volumes:
      - ./:/app/